@host = http://localhost:8000

### Insert items into review
POST http://localhost:8000/review
Accept: application/json
Content-Type: application/json

{
    "coffee_shop_id": "feferon",
    "user_id": "feferon",
    "rating": 5, 
    "description": "feferon"
}
