# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orders_pb2 as orders__pb2


class OrderServiceStub(object):
    """The order service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserOrders = channel.unary_unary(
                '/orders.OrderService/GetUserOrders',
                request_serializer=orders__pb2.UserOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.UserOrderResponse.FromString,
                )


class OrderServiceServicer(object):
    """The order service definition.
    """

    def GetUserOrders(self, request, context):
        """Sends a request for user orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserOrders,
                    request_deserializer=orders__pb2.UserOrderRequest.FromString,
                    response_serializer=orders__pb2.UserOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """The order service definition.
    """

    @staticmethod
    def GetUserOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.OrderService/GetUserOrders',
            orders__pb2.UserOrderRequest.SerializeToString,
            orders__pb2.UserOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
