# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"#\n\x10UserOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"2\n\x11UserOrderResponse\x12\x1d\n\x06orders\x18\x01 \x03(\x0b\x32\r.orders.Order\"B\n\tOrderItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x12\n\nunit_price\x18\x03 \x01(\x02\"\x80\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0btotal_price\x18\x03 \x01(\x02\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12 \n\x05items\x18\x05 \x03(\x0b\x32\x11.orders.OrderItem\x12\x12\n\norder_date\x18\x06 \x01(\t2T\n\x0cOrderService\x12\x44\n\rGetUserOrders\x12\x18.orders.UserOrderRequest\x1a\x19.orders.UserOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERORDERREQUEST']._serialized_start=24
  _globals['_USERORDERREQUEST']._serialized_end=59
  _globals['_USERORDERRESPONSE']._serialized_start=61
  _globals['_USERORDERRESPONSE']._serialized_end=111
  _globals['_ORDERITEM']._serialized_start=113
  _globals['_ORDERITEM']._serialized_end=179
  _globals['_ORDER']._serialized_start=182
  _globals['_ORDER']._serialized_end=310
  _globals['_ORDERSERVICE']._serialized_start=312
  _globals['_ORDERSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
