# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 27000:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  fastapi_app:
    environment:
      - GOOGLE_CLIENT_ID=476984822533-s6526ehc2lbn5a0ma6clk6bbmepg5nb6.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo